baseURL = "https://ocristian.github.io"

languageCode = "en-us"
DefaultContentLanguage = "en"

title = "ocristian.github.io"
theme = "anatole"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Google Analytics
googleAnalytics = "G-FTW72MSPC9"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "pLá!"
author = "Cristian Silva"
description = ""
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = []
mainSections = ["post"]
images = ["favicons/apple-touch-icon.png"]
doNotLoadAnimations = false
gtagId = "G-FTW72MSPC9"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/_ocristian"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/ocristian"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/ocristian/"

[[params.socialIcons]]
icon = "fas fa-rss"
title = "RSS"
url = "/index.xml"

## Menu items
[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"